name: sparrow_dio
description: sparrow团队完成的对dio的封装，实现dio的async await调用以及回调方式的调用.
version: 0.6.0

homepage: https://github.com/hanguangbaihuo/sparrow_dio

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity: ^3.0.6 # 检查手机联网情况
  dio: ^4.0.0 # 网络请求
  bot_toast: ^4.0.1 # toast组件
  sparrow_utils: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
