name: sparrow_dio
description: sparrow团队完成的对dio的封装，实现dio的async await调用以及回调方式的调用.
version: 0.13.1+1

homepage: https://github.com/hanguangbaihuo/sparrow_dio

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^1.0.6
  dio: ^4.0.0 # 网络请求
  pretty_dio_logger: ^1.2.0-beta-1
  sparrow_utils: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
